sudo: false
language: ruby
rvm:
  - 2.2.5
before_install: gem install bundler -v 1.12.5
script: bundle exec rake
notifications:
  email:
    recipients:
      - jpriddle@me.com
    on_success: never
    on_failure: always
